CREATE TABLE IF NOT EXISTS Players
(
    HANDLE TEXT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    LATEST_GAME INTEGER NOT NULL,
    UNIQUE(HANDLE)
);

CREATE TABLE IF NOT EXISTS Games
(
    ID INTEGER PRIMARY KEY NOT NULL,
    PATCH TEXT NOT NULL,
    CREEPS TEXT NOT NULL,
    GAMEMODE TEXT NOT NULL,
    END INTEGER NOT NULL,
    UNIQUE(ID)
);

CREATE TABLE IF NOT EXISTS GamePlayers
(
    PLAYER_ID INTEGER NOT NULL,
    TEAM TEXT NOT NULL,
    WON INTEGER NOT NULL,
    PLAYER_HANDLE TEXT NOT NULL,
    GAME_ID INTEGER NOT NULL,
    FOREIGN KEY(PLAYER_HANDLE) REFERENCES Players(HANDLE),
    FOREIGN KEY(GAME_ID) REFERENCES Games(ID)
);

CREATE TABLE IF NOT EXISTS Towers
(
    WAVE INTEGER NOT NULL,
    TOWER_TYPE TEXT NOT NULL,
    GAME_ID INTEGER NOT NULL,
    HANDLE TEXT NOT NULL,
    PLAYER_ID INTEGER NOT NULL,
    FOREIGN KEY(GAME_ID) REFERENCES Games(ID),
    FOREIGN KEY(HANDLE) REFERENCES Players(HANDLE),
    FOREIGN KEY(PLAYER_ID) REFERENCES GamePlayers(PLAYER_ID)
);

CREATE TABLE IF NOT EXISTS Sends
(
    WAVE INTEGER NOT NULL,
    SEND_TYPE TEXT NOT NULL,
    GAME_ID INTEGER NOT NULL,
    HANDLE TEXT NOT NULL,
    PLAYER_ID INTEGER NOT NULL,
    FOREIGN KEY(GAME_ID) REFERENCES Games(ID),
    FOREIGN KEY(HANDLE) REFERENCES Players(HANDLE),
    FOREIGN KEY(PLAYER_ID) REFERENCES GamePlayers(PLAYER_ID)
);

CREATE TABLE IF NOT EXISTS Builders
(
    WAVE INTEGER NOT NULL,
    BUILDER TEXT NOT NULL,
    GAME_ID INTEGER NOT NULL,
    HANDLE TEXT NOT NULL,
    PLAYER_ID INTEGER NOT NULL,
    FOREIGN KEY(GAME_ID) REFERENCES Games(ID),
    FOREIGN KEY(HANDLE) REFERENCES Players(HANDLE),
    FOREIGN KEY(PLAYER_ID) REFERENCES GamePlayers(PLAYER_ID)
);

CREATE TABLE IF NOT EXISTS Workers
(
    WORKER_NUMBER INTEGER NOT NULL,
    WORKER_WAVE INTEGER NOT NULL,
    GAME_ID INTEGER NOT NULL,
    HANDLE TEXT NOT NULL,
    PLAYER_ID INTEGER NOT NULL,
    FOREIGN KEY(GAME_ID) REFERENCES Games(ID),
    FOREIGN KEY(HANDLE) REFERENCES Players(HANDLE),
    FOREIGN KEY(PLAYER_ID) REFERENCES GamePlayers(PLAYER_ID)
);

CREATE TABLE IF NOT EXISTS Upgrades
(
    UPGRADE_NUMBER INTEGER NOT NULL,
    UPGRADE_WAVE   INTEGER NOT NULL,
    GAME_ID INTEGER NOT NULL,
    HANDLE TEXT NOT NULL,
    PLAYER_ID INTEGER NOT NULL,
    FOREIGN KEY (GAME_ID) REFERENCES Games (ID),
    FOREIGN KEY (HANDLE) REFERENCES Players (HANDLE),
    FOREIGN KEY (PLAYER_ID) REFERENCES GamePlayers (PLAYER_ID)
);